name: Terraform CI

on:
  # 1. Run on every push to your feature branch
  push:
  branches:
    - test/terraform
  paths:
    - 'terraform/**'
    - '**.tf'
    - '.github/workflows/terraform-ci.yml'

  # 2. Run when you open a PR targeting main
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '**.tf'
      - '.github/workflows/terraform-cd.yml'

jobs:
  terraform-checks:
    name: Terraform Validation
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Lint
        uses: terraform-linters/tflint-action@v4