name: Terraform CI

on:
  # 1. Run on every push to your feature branch
  push:
    branches:
      - test/terraform
    paths:
      - 'terraform/**'
      - '**.tf'
      - '.github/workflows/terraform-ci.yml'

  # 2. Run when you open a PR targeting main
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '**.tf'
      - '.github/workflows/terraform-ci.yml'

env:
  
  AWS_REGION : "ap-south-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  terraform-ci:
    name: Run Terraform CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, staging, prod]

    defaults:
      run:
        working-directory: terraform/environment/${{ matrix.env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # - name: Debug paths
      #   run: |
      #     echo "PWD: $(pwd)"
      #     echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      #     ls -R

      - name: Show environment
        run: echo "Running for ${{ matrix.env }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.6.0   # pin version (important for consistency)
      # Setup Python (for pytest + tftest)
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest tftest

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: Run TFLint
        run: | 
          tflint --init
          tflint --recursive
      # Terraform Plan (NO APPLY)
      - name: Terraform Plan
        run: terraform plan -input=false -lock=false
      # Run Unit Tests (pytest)
      - name: Run pytest (unit)
        run: pytest ../../../tests/unit/test_terraform/
      # Run Integration Tests (tftest with mocks)
      - name: Run tftest (integration)
        run: pytest ../../../tests/integration/test_terraform/